### ISSUE TITLE
To implement the LTCC dataset in your code？

### ISSUE THREAD

**Issue by planet-miemie** [QizaoWang/CAMC-CCReID#1]
The provided code does not include any preprocessing operations for the "ltcc" dataset. Could you please clarify what specific operations you would like to perform on the "ltcc" dataset? The code you provided defines an img_factory dictionary with two keys: 'market1501' and 'celeb'. Each key is associated with a corresponding class (Market1501 and CelebreID, respectively). However, there is no mention of the "ltcc" dataset in the code snippet. Additionally, there is no "ltcc.py" file related to this.

**Comment by QizaoWang** [comment]
Thank you for your interest in our work. You can simply add the processing code for the LTCC dataset and then add support for it in 'data_manager.py'. For convenience, we have added the relevant code.

**Comment by planet-miemie** [comment]
Hello Professor,


According to the code you provided, I encountered a new issue while reproducing the LTCC dataset. The training process did not reach 100% completion, and the code did not interrupt as indicated by the red box in the image. I would like to ask if this is normal since I haven't encountered a similar issue with the Market1501 and Celeb datasets before. I'm looking forward to your response.


Best regards






杨欣馨
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QizaoWang/CAMC-CCReID"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月4日(星期二) 中午1:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [QizaoWang/CAMC-CCReID] To implement the LTCC dataset in your code？ (Issue #1)





 
Thank you for your interest in our work. You can simply add the processing code for the LTCC dataset and then add support for it in 'data_manager.py'. For convenience, we have added the relevant code.
