### ISSUE TITLE
question about code

### ISSUE THREAD

**Issue by beauty2000** [QizaoWang/CAMC-CCReID#4]
Do I need to use this pre-trained model “pose_hrnet_w48_384x288.pth” for testing every dataset? I looked at it below the training phase and I didn't find any other models.

**Comment by beauty2000** [comment]
![Uploading 屏幕截图 2024-05-14 172804.png…]()

**Comment by beauty2000** [comment]
![Uploading 屏幕截图 2024-05-14 172804.png…]()

**Comment by beauty2000** [comment]
![Uploading 屏幕截图 2024-05-14 172804.png…]()

**Comment by QizaoWang** [comment]
The off-the-shelf estimator is used to obtain heatmaps of human postures during the training and testing phases on all datasets. “pose_hrnet_w48_384x288.pth” is the pre-trained weight of the frozen estimator. Before testing our method on the Re-ID dataset, you should train the backbone and other modules, which can be done following our guidance for Training.

**Comment by beauty2000** [comment]
> The off-the-shelf estimator is used to obtain heatmaps of human postures during the training and testing phases on all datasets. “pose_hrnet_w48_384x288.pth” is the pre-trained weight of the frozen estimator. Before testing our method on the Re-ID dataset, you should train the backbone and other modules, which can be done following our guidance for Training.

I currently have limited computing power, can you provide other parts of the pre-trained model?

**Comment by QizaoWang** [comment]
Our trained model checkpoints are currently unavailable. It will be easy to train following our guidance. Some free computing platforms like Google Colab may be helpful for your training.
